learning_rate: 0.03
weight_decay: 0.0
num_steps: 2000
decay_type: cosine
warmup_steps: 400
max_grad_norm: 1.0
fp16_opt_level: O0
loss_scale: 0.0
name: CIFAR
model_type: ViT-B_32
pretrained_dir: ViT-B_32.npz
output_dir: output
seed: 42
gradient_accumulation_steps: 1
fp16: false
img_size: 224
train_batch_size: 512
eval_batch_size: 64
eval_every: 100
num_classes: 100
